config/routes.rb
Rails.application.routes.draw do
  resources :participants, path: 'paticipantes', except: [:index] do
    member do
      get :certificates_download, action: 'certificates_download'
    end
    collection do
      get :index
      post :import_from_csv
    end
  end
  resources :frequences, path: 'frequencia', except: [:edit, :destroy, :create] do
    collection do
      get :edit
    end
  end
  resources :type_participations, path: 'tipos-participacao'
  resources :certificate_templates, path: 'templates-de-certificados' do
    collection do
      get :load_selected_signatures
    end
    member do
      get 'arquive'
      get 'unarchive'
    end
  end
  resources :event_requests, path: 'solicitacoes-eventos' do
    member do
      get 'forward_the_request', action: 'forward_the_request'
      get 'generate_event', action: 'generate_event'
      post 'return_for_changes', action: 'return_for_changes'
    end
    collection do
      get 'my_requests'
    end
  end
  resources :courses, path: 'cursos'
  resources :events, path: 'eventos' do
    member do
      get 'release_issuing_certificates', action: 'release_issuing_certificates'
    end
  end
  resources :event_categories, path: 'categorias-de-eventos'
  resources :certificate_signatures, path: 'assinaturas-de-certificado' do
    collection do
      get 'autocomplete_by_name_or_role'
    end
    member do
      get 'arquive'
      get 'unarchive'
    end
  end
  resources :permissions, path: 'permissoes', except: [:new, :destroy] do
    collection do
      get 'recreate_and_update_all'
    end
  end
  resources :profiles, path: 'perfis'
  devise_for :users,
             controllers: { omniauth_callbacks: "omniauth_callbacks" },
             :skip => [:registrations]

  resources :users, path: 'usuarios' do
    collection do
      get 'new_registration'
      get 'success_registration'
      post 'registration_save'
    end
  end

# get 'users/:id/complete_registration', to: 'users#complete_registration'

  get 'people/name', to: 'people#name'
  get 'validar/:certificate_hash', to: 'participants#validate_certificate'
  get 'validar/', to: 'participants#validate_certificate'
  get 'people/autocomplete_by_cpf', to: 'people#autocomplete_by_cpf'

  root to: "home#index"

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/participant.rb
require "zlib"
require 'securerandom'

class Participant < ApplicationRecord
#   belongs_to :person, required: false
  belongs_to :frequence, required: false
  belongs_to :type_participation, required: false
  belongs_to :event, required: false

  before_update :generate_hash

  before_validation :format_cpf
  validates_cpf_format_of :cpf

  enum status: { confirmed_subscription: 1,
                 awaiting_certificate: 2,
                 certified: 4,
                 unsubscribed: 3 }

  def full_name
    [self.name, self.surname].join(' ')
  end

  def workload_s
    "#{workload} #{workload == 1 ? 'Hora' : 'Horas'}"
  end

  private

  def generate_hash
    if certified? && !self.certificate_hash.present?
      self.certificate_hash = Zlib.adler32(SecureRandom.uuid).to_s(16)
    end
  end

  def format_cpf
    return unless self.cpf.present?

    cpf_numbers = cpf.gsub(/\D/, '')
    self.cpf = CPF.new(cpf_numbers).formatted
  end
end

app/controllers/participants_controller.rb
require "csv"

class ParticipantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:validate_certificate]
  load_and_authorize_resource except: [:validate_certificate]

  before_action :set_participant, only: [:show, :edit, :update, :destroy, :certificates_download]
  before_action :set_list_for_select, only: [:edit, :new, :index]
  before_action :set_filter_object, only: [:index]

  # GET /participants
  def index
    @participants = FindParticipant.find(@filter, page_params, [cpf: current_user.person.cpf, status: :certified])
  end

  # GET /participants/1
  def show
  end

  # GET /participants/new
  def new
    if params[:event].present? && params[:frequence].present?
      @participant = Participant.new(event_id: params[:event], frequence_id: params[:frequence])
    else
      flash[:error] = "Evento ou frequência não encontrados"
    end
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  def create
    @form_id = params[:id_form]
    @participant = Participant.new(participant_params)
    @participant.status = :awaiting_certificate
    if @participant.save
      flash[:success] = 'Participante adicionado com sucesso'
    end
  end

  def certificates_download
    participants = Participant.where(id: [@participant.id])

    certificates = CertificateGenerator.call(participants)

    s_certificates = render_to_string(partial: 'participants/reports/certificate', layout: false, locals: { certificates: certificates })

    send_pdf(s_certificates, 'certificates.pdf')
  end

  def validate_certificate
    if params[:certificate_hash].present?
      participant = Participant.find_by(certificate_hash: params[:certificate_hash])

      if participant.present?
        certificates = CertificateGenerator.call([participant])
        @certificate = certificates.first
      end
    end

  end

  # PATCH/PUT /participants/1
  def update
    if @participant.update(participant_params)
      flash[:success] = 'Participante atualizado com sucesso'
    end
  end

  # DELETE /participants/1
  def destroy
    if @participant.present?
      @participant.destroy
      flash[:success] = 'Participante removido com sucesso'
    else
      flash[:warning] = 'Participante não existe'
    end
  end

  def import_from_csv
    if params[:event].present? && params[:frequence].present?
      @event = Event.find(params[:event].to_i)
      @frequence = Frequence.find(params[:frequence].to_i)
      @type_participation = TypeParticipation.find_by_key(:ouvinte)
      @arquive = Archive.new(arquive_params)
      @arquive.origin = @event
      @arquive.save

      File.open("planilha.csv", 'w') { |file| file.write(@arquive.content.force_encoding("UTF-8")) }

      file = File.open("planilha.csv", "r")
      CSV.parse(file).map { |x| x[0] }.each_with_index do |row, i|
        next if i == 0
        data = row.split(";")

        participant = Participant.find_or_create_by(event: @event,
                                                    frequence: @frequence,
                                                    cpf: data[3])

        participant.name = data[0]
        participant.surname = data[1]
        participant.registration = data[4]
        participant.cpf = data[3]
        participant.email = data[2]
        participant.workload = @event.workload
        participant.type_participation = @type_participation
        participant.status = :awaiting_certificate

        participant.save
      end
      file.close
      @participants = Participant.where(event_id: @event, frequence_id: @frequence)
      flash[:success] = "Importação realizada com sucesso"
    else
      flash[:error] = "Evento ou frequência não encontrados"
    end
  end

  private

  def set_filter_object
    @params = params[:filter] || {}
    @filter = Filter.new({
                             name: @params[:name],
                             event_category: @params[:event_category],
                             type_participation: @params[:type_participation],
                             start_date: @params[:start_date],
                             closing_date: @params[:closing_date],
                             workload: @params[:workload]
                         })
  end

  def set_list_for_select
    @event_categories = EventCategory.select(:name, :id).map { |k, v| [k.name, k.id] }
    @type_participations = TypeParticipation.select(:name, :id).map { |k, v| [k.name, k.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_participant
    if Participant.exists?(params[:id])
      @participant = Participant.find(params[:id])
    end
  end

  # Only allow a trusted parameter "white list" through.
  def participant_params
    params.require(:participant).permit(:person_id, :frequence_id, :type_participation_id, :email,
                                        :event_id, :status, :workload, :cpf, :name, :surname, :registration)
  end

  # Only allow a trusted parameter "white list" through.
  def arquive_params
    params.require(:arquive).permit(:file)
  end
end

app/views/participants/_form.html.erb
<%= form_with(model: participant, remote: true) do |fp| %>
  <%= modal("#{fp.object.id || 'new-participant'}", "#{participant.new_record? ? 'Adicionar' : 'Editar'} Participante", size: :xl) do %>
    <%= modal_body do %>
      <%= fp.hidden_field :event_id %>
      <%= fp.hidden_field :frequence_id %>
      <div class="row pl-2 pr-2" style="z-index: 100000">
        <div class="col-sm-12">
          <span id="errors"></span>
        </div>
        <div class="col-sm-3">
          <div class="form-group">
            <%= fp.label :name %>
            <%= fp.text_field :name, class: 'form-control', placeholder: true %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= fp.label :surname %>
            <%= fp.text_field :surname, class: 'form-control', placeholder: true %>
          </div>
        </div>
        <div class="col-sm-5">
          <div class="form-group">
            <%= fp.label :email %>
            <%= fp.text_field :email, class: 'form-control', placeholder: true %>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="form-group">
            <% workload = participant.workload || participant.event.workload %>
            <%= fp.label :workload %>
            <%= fp.text_field :workload, value: workload, class: 'form-control', placeholder: true %>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-group">
            <%= fp.label :registration %>
            <%= fp.text_field :registration, class: 'form-control', placeholder: true %>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="form-group">
            <%= fp.label :cpf %>
            <%= fp.text_field :cpf, class: 'form-control cpf-mask', placeholder: true %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= fp.label :type_participation %>
            <%= fp.select(:type_participation_id, @type_participations,
                          { include_blank: true },
                          { size: 5, class: 'form-control choices' }) %>
          </div>
        </div>
      </div>
    <% end %>
    <%= modal_footer do %>
      <%= button_tag(class: 'btn btn-primary btn-icon btn-1 btn-simple') do %>
        <i class="fa fa-floppy-o"></i> Salvar
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/participants/_show_certificate.html.erb
<div id="certificate-frame" style="background-image: url('<%= cert[:url_backgroud] %>');">
  <div id="certificate-text-frame">
    <div id="certificate-text-content">
      <%= cert[:text].html_safe %>
    </div>
  </div>
  <div id="certificate-signatures-frame">
    <div id="" class="col-md-12">
      <div class="row">
        <% cert[:certificate_signatures].each do |signature| %>
          <div class="col text-center">
            <img id="scanned-signature" class="scanned-signature"
                 src="<%= signature[:url] %>"
                 alt="<%= signature[:name] %>"/>
            <span id="name" class="d-block text-black font-weight-bold font-italic"><%= signature[:name] %></span>
            <span id="role" class="d-block"><%= signature[:role] %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    function loadPreview() {
        const heigth_a4_ref = 807.467
        const width_a4_ref = 1142

        const certificate_frame = $('#certificate-frame');
        const certificate_text_frame = $('#certificate-text-frame');
        const certificate_signatures_frame = $('#certificate-signatures-frame');

        const width = $($('.container')[0]).width() || certificate_frame.parent().width();
        const height = parseInt(width) * heigth_a4_ref / width_a4_ref;

        certificate_frame.css('height', height);

        const top_text = parseInt(height) * 310 / heigth_a4_ref;
        const height_text = parseInt(height) * 220 / heigth_a4_ref;

        certificate_text_frame.css({
            'top': `${top_text}px`,
            'height': `${height_text}px`,
            'padding-left': '100px',
            'line-height': `${height_text}px`,
            'padding-right': '100px',
        });

        const top_signatures = (parseInt(height) * 570 / heigth_a4_ref) - height_text;

        certificate_signatures_frame.css({
            'top': `${top_signatures}px`,
            'padding-left': '100px',
            'padding-right': '100px',
        });
    }
</script>

app/views/participants/_table.html.erb
<table class="table" id="<%= id %>">
  <thead class="thead-light">
  <tr>
    <th class="pt-3 pb-3 pl-2 pr2 bold">Nome Completo</th>
    <th class="pt-3 pb-3 pl-2 pr2 bold">Email</th>
    <th class="pt-3 pb-3 pl-2 pr2 bold">C. Horária</th>
    <th class="pt-3 pb-3 pl-2 pr2 bold">Matrícula</th>
    <th class="pt-3 pb-3 pl-2 pr2 bold">CPF</th>
    <th class="pt-3 pb-3 pl-2 pr2 bold">Participação</th>
    <th style="width: 1%;" class="pt-3 pb-3 pl-2 pr2 text-center bold">Ações</th>
  </tr>
  </thead>
  <tbody>
  <% participants.each do |participant| %>
    <tr id="<%= participant.id %>'">
      <td class="p-2"><%= participant.name %> <%= participant.surname %></td>
      <td class="p-2"><%= participant.email %></td>
      <td class="p-2"><%= participant.workload %> Horas</td>
      <td class="p-2"><%= participant.registration %></td>
      <td class="p-2"><%= participant.cpf %></td>
      <td class="p-2"><%= participant.type_participation.name %></td>
      <td style="width: 1%" class="p-2" colspan="3">
        <% url = participant.id.present? ? participant_path(id: participant.id) : '#' %>
        <%= link_to span_icon('', 'edit'), edit_participant_path(participant),
                    class: 'btn btn-primary btn-icon btn-sm', remote: true,
                    data: { toggle: 'tooltip', placement: 'bottom' }, title: "Editar" %>
        <%= link_to span_icon('', 'trash'), 'javascript:void(0)', onclick: 'remove(this)',
                    class: 'btn btn-danger btn-icon btn-sm',
                    data: { toggle: 'tooltip', placement: 'bottom', url: url }, title: "Excluir" unless participant.certified? %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/participants/create.js.erb
<% if @participant.errors.any? %>
  $('#new-participant-modal').find('#errors').html('<%= j validations_errors(@participant, margin: 0) %>')
<% else %>
  <% flash.each do |flash, message| %>
    Toast.fire({
        icon: '<%= flash %>',
        title: '<%= message %>'
    })
  <% end %>
  $('#new-participant-modal').modal('hide');

  <% event_id = @participant.event.id %>
  <% participants = @participant.frequence.participants&.select { |x| x.event_id == event_id } || [] %>
  $('#<%= event_id %>').replaceWith('<%= j render 'participants/table', participants: participants, id: event_id %>');
<% end %>

app/views/participants/destroy.js.erb
<% if @participant.present? %>
  <% flash.each do |flash, message| %>
    Toast.fire({
        icon: '<%= flash %>',
        title: '<%= message %>'
    })
  <% end %>
  <% event_id = @participant.event.id %>
  <% participants = @participant.frequence.participants&.select { |x| x.event_id == event_id } || [] %>
  $('#<%= event_id %>').replaceWith('<%= j render 'participants/table', participants: participants, id: event_id %>');
<% end %>

app/views/participants/edit.js.erb
$("#modal").html('<%= j render('form', participant: @participant) %>');
$('#<%= @participant.id %>-modal').modal();
inicializeInputs()

app/views/participants/import_from_csv.js.erb
<% if  @participants.present? %>
  $('#<%= @event.id %>').replaceWith('<%= j render 'participants/table', participants: @participants, id: @event.id %>');
<% end %>

<% flash.each do |flash, message| %>
  Toast.fire({
      icon: '<%= flash %>',
      title: '<%= message %>'
  })
<% end %>

app/views/participants/index.html.erb
<div class="clearfix">
  <div class="float-left">
    <%= page_title("Meus certificados") %>
  </div>
  <div class="float-right pt-2 mr-4">
    <%= icon_link i18n_word(:filter), 'filter', "#collapseFilter", class: 'text-dark', data: { toggle: 'collapse' },
                  aria: { expanded: "false", controls: "collapseFilter" } %>
  </div>
</div>

<%= card_filter(params[:show_filter]) do %>
  <%= form_for(@filter, url: participants_path, local: true, method: :get, id: 'new_filter') do |f| %>
    <%= hidden_field_tag :show_filter, value: true %>
    <div class="row">
      <div class="col-md-5">
        <div class="form-group">
          <%= f.text_field :name, class: 'form-control', placeholder: i18n_placeholder(:participant, :event) %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.select(:type_participation, @type_participations,
                       { include_blank: i18n_placeholder(:participant, :type_participation) },
                       { class: 'form-control choices',
                         data: { trigger: '' }, }) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= f.select(:event_category, @event_categories,
                       { include_blank: i18n_placeholder(:participant, :event_category) },
                       { class: 'form-control choices',
                         data: { trigger: '' }, }) %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.text_field :workload, class: 'form-control', placeholder: i18n_placeholder(:participant, :workload) %>
        </div>
      </div>
      <div class="col-md-2">
        <%= f.date_picker :start_date, placeholder: i18n_placeholder(:event, :start_date),
                          value: f.object.start_date, hide_label: true %>
      </div>
      <div class="col-md-2 mr-auto">
        <%= f.date_picker :closing_date, placeholder: i18n_placeholder(:event, :closing_date),
                          value: f.object.closing_date, hide_label: true %>
      </div>
      <div class="col-md-auto nowrap">
        <%= button_tag(:class => "btn btn-primary btn-icon btn-1 btn-simple pull") do %>
          <span><i class="fa fa-search"></i></span>
        <% end %>
        <%= clear_form_button %>
      </div>
    </div>
  <% end %>
<% end %>

<table class="table table-flush">
  <thead class="thead-light">
  <tr class="bg-primary">
    <th class="bold break-text"><%= i18n_model(:participant, :event) %></th>
    <th class="bold"><%= i18n_model(:event, :event_category_id) %></th>
    <th class="bold"><%= i18n_model(:participant, :type_participation) %></th>
    <th class="bold"><%= i18n_model(:event, :start_date) %></th>
    <th class="bold"><%= i18n_model(:event, :closing_date) %></th>
    <th class="bold"><%= i18n_model(:participant, :workload) %></th>
    <th style="width:1%;" class="text-center bold" colspan="3"><%= i18n_word(:download) %></th>
  </tr>
  </thead>

  <tbody>
  <% @participants.each do |participant| %>
    <tr>
      <td class="break-text"><%= participant.event.name %></td>
      <td><%= participant.event.event_category.name %></td>
      <td><%= participant.type_participation.name %></td>
      <td><%= participant.event.start_date.strftime('%d/%m/%Y %H:%M') %></td>
      <td><%= participant.event.closing_date.strftime('%d/%m/%Y %H:%M') %></td>
      <td><%= participant.workload %> Hora (s)</td>
      <td class="text-center">
        <%= link_to '<span><i class="fa fa-download"></i></span>'.html_safe, certificates_download_participant_path(participant),
                    class: 'btn btn-primary btn-icon btn-sm btn-simple',
                    data: { toggle: 'tooltip', placement: 'bottom' }, title: "Baixar certificado" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="row justify-content-center">
  <%= paginate @participants %>
</div>

app/views/participants/new.js.erb
$("#modal").html('<%= j render('form', participant: @participant) %>');
$('#new-participant-modal').modal();
inicializeInputs()

app/views/participants/update.js.erb
<% if @participant.errors.any? %>
  $('#<%= @participant.id %>-modal').find('#errors').html('<%= j validations_errors(@participant, margin: 0) %>')
<% else %>
  $('#<%= @participant.id %>-modal').modal('hide');

  <% flash.each do |flash, message| %>
    Toast.fire({
        icon: '<%= flash %>',
        title: '<%= message %>'
    })
  <% end %>

  <% event_id = @participant.event.id %>
  <% participants = @participant.frequence.participants&.select { |x| x.event_id == event_id } || [] %>
  $('#<%= event_id %>').replaceWith('<%= j render 'participants/table', participants: participants, id: event_id %>');
<% end %>

app/views/participants/validate_certificate.html.erb
<div class="clearfix">
  <div class="float-left">
    <%= page_title("Validar certificado") %>
  </div>
</div>
<div class="row">
  <div class="col-md mr-auto">
    <%= text_field_tag :certificate_hash, params[:certificate_hash], class: 'form-control', placeholder: 'Código do certificado', hide_label: true %>
  </div>
  <div class="col-md-auto nowrap">
    <%= button_tag(:class => "btn btn-primary btn-icon btn-1 btn-simple pull", onclick: 'validar()') do %>
      <span><i class="fa fa-search"></i></span>
    <% end %>
  </div>
</div>
<div id="success-message" class="row mt-3" style="display: none;">
  <div class="col-sm-12">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
      <span class="alert-inner--text" style="font-size: 18pt">Certificado encontrado com sucesso!!!</span>
    </div>
  </div>
</div>
<div class="row mt-3">
  <div class="col">
    <div id='preview-certificate'>
      <%= render('participants/show_certificate', cert: @certificate) if @certificate.present? %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(() => {
        <% if @certificate.present? %>
        $("#success-message").show();
        loadPreview();
        <% elsif params[:certificate_hash].present? %>
        Swal.fire({
            title: 'Certificado não encontrado!',
            icon: 'error'
        });
        <% end %>
    })

    function validar() {
        $.ajax({
            data: {
                certificate_hash: $('#certificate_hash').val()
            },
            type: "GET",
            url: "<%= validar_path %>",
            dataType: "script"
        });
    }
</script>

app/views/participants/validate_certificate.js.erb
showComponents();

function showComponents() {
    const preview_certificate = $("#preview-certificate")
    const success_message = $("#success-message")

    <% if @certificate.present? %>
    preview_certificate.html('<%= j render('participants/show_certificate', cert: @certificate) %>')
    preview_certificate.show();
    success_message.show();
    loadPreview();
    <% else %>
    Swal.fire({
        title: 'Certificado não encontrado!',
        icon: 'error'
    });
    preview_certificate.hide();
    success_message.hide();
    <% end %>
}