config/routes.rb
Rails.application.routes.draw do
  resources :participants, path: 'paticipantes', except: [:index] do
    member do
      get :certificates_download, action: 'certificates_download'
    end
    collection do
      get :index
      post :import_from_csv
    end
  end
  resources :frequences, path: 'frequencia', except: [:edit, :destroy, :create] do
    collection do
      get :edit
    end
  end
  resources :type_participations, path: 'tipos-participacao'
  resources :certificate_templates, path: 'templates-de-certificados' do
    collection do
      get :load_selected_signatures
    end
    member do
      get 'arquive'
      get 'unarchive'
    end
  end
  resources :event_requests, path: 'solicitacoes-eventos' do
    member do
      get 'forward_the_request', action: 'forward_the_request'
      get 'generate_event', action: 'generate_event'
      post 'return_for_changes', action: 'return_for_changes'
    end
    collection do
      get 'my_requests'
    end
  end
  resources :courses, path: 'cursos'
  resources :events, path: 'eventos' do
    member do
      get 'release_issuing_certificates', action: 'release_issuing_certificates'
    end
  end
  resources :event_categories, path: 'categorias-de-eventos'
  resources :certificate_signatures, path: 'assinaturas-de-certificado' do
    collection do
      get 'autocomplete_by_name_or_role'
    end
    member do
      get 'arquive'
      get 'unarchive'
    end
  end
  resources :permissions, path: 'permissoes', except: [:new, :destroy] do
    collection do
      get 'recreate_and_update_all'
    end
  end
  resources :profiles, path: 'perfis'
  devise_for :users,
             controllers: { omniauth_callbacks: "omniauth_callbacks" },
             :skip => [:registrations]

  resources :users, path: 'usuarios' do
    collection do
      get 'new_registration'
      get 'success_registration'
      post 'registration_save'
    end
  end

# get 'users/:id/complete_registration', to: 'users#complete_registration'

  get 'people/name', to: 'people#name'
  get 'validar/:certificate_hash', to: 'participants#validate_certificate'
  get 'validar/', to: 'participants#validate_certificate'
  get 'people/autocomplete_by_cpf', to: 'people#autocomplete_by_cpf'

  root to: "home#index"

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/event.rb
class Event < ApplicationRecord
  include CSituation

  before_validation :set_file_extensions

  attr_accessor :current_user, :draft

  belongs_to :image, required: false
  belongs_to :parent_event, class_name: 'Event', foreign_key: 'event_id', required: false
  belongs_to :event_category
  belongs_to :certificate_template, required: false
  belongs_to :situation, required: false
  has_one :frequence
  has_many :situations, -> { order('created_at asc') }, as: :origin
  has_many :child_events, :class_name => "Event"
  has_many :participants, foreign_key: :event_id
  has_and_belongs_to_many :oriented_activities # use alias guiding

  validates_presence_of :name, :start_date, :closing_date, :event_category, :workload

  accepts_nested_attributes_for :image, allow_destroy: true, reject_if: -> (x) { x[:file].nil? }
  accepts_nested_attributes_for :oriented_activities, allow_destroy: true
  accepts_nested_attributes_for :child_events, allow_destroy: true

  scope :no_draft, -> {
    joins(situation: [:key_situation]).where('key_situations.key != ?', :draft).distinct
  }

  def create_initial_situation
    return if situation.present? || parent_event.present? || deferred? || !current_user.present?

    self.situations.create(person: current_user.person,
                           key_situation: KeySituation.find_by(key: :deferred))
  end

  def approve_event
    return if deferred?

    self.situations.create(person: current_user.person,
                           key_situation: KeySituation.find_by(key: :deferred))

    set_current_situation
  end

  def release_issuing_certificates
    load_and_select_templates

    return if !self.errors.empty? || parent_event.present?

    self.frequence.participants&.each do |participant|
      participant.update_attribute(:status, :certified) unless participant.certified?
    end

    self.situations.create(person: current_user.person,
                           key_situation: KeySituation.find_by(key: :released_certificates))

    set_current_situation
  end

  def can_action?(action)
    case self.situation&.key_situation&.key&.to_sym
    when :deferred
      [:show, :edit, :destroy,
       :release_issuing_certificates, :edit_frequences].include?(action)
    when :draft
      [:show,].include?(action)
    when :released_certificates
      [:show, :edit_frequences, :release_issuing_certificates,].include?(action)
    else
      false
    end
  end

  def full_name
    [parent_event&.name, self.name].compact.join(' - ')
  end

  private

  def load_and_select_templates
    categorias_sem_template = []

    if child_events.any?
      child_events.each do |event|
        template = CertificateTemplate::default_certificate(event.event_category_id)
        if template.present?
          event.update_attribute(:certificate_template_id, template.id)
        else
          categorias_sem_template << event.event_category.name
        end
      end
    else
      template = CertificateTemplate::default_certificate(self.event_category_id)
      if template.present?
        self.certificate_template = template
      else
        categorias_sem_template << self.event_category.name
      end
    end

    message = "Não foi encontrado um template padrão para a(s) categoria(s)
               <b>#{categorias_sem_template.join('</b>, <b>')}</b>"
    self.errors.add(:base, message) if categorias_sem_template.any?
  end

  # Defines the allowed image formats
  def set_file_extensions
    self.image.allowed_extensions = [:png, :jpg, :jpeg] if self.image.present?
  end
end

app/models/oriented_activity.rb
class OrientedActivity < ApplicationRecord
  alias_attribute :advisors, :people

  belongs_to :event_category

  has_and_belongs_to_many :people # use alias guiding
  has_and_belongs_to_many :guideds

  accepts_nested_attributes_for :people
  accepts_nested_attributes_for :guideds, allow_destroy: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  load_and_authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy, :release_issuing_certificates]
  before_action :set_list_for_select, only: [:index, :new, :edit, :update, :create]
  before_action :verify_action, only: [:edit, :update, :destroy]
  before_action :set_filter_object, only: [:index]

  # GET /events
  def index
    @events = FindEvent.find(@filter, page_params)
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # GET /events/1/edit
  def release_issuing_certificates
    if @event.frequence.present? && @event.frequence.participants.any?
      @event.current_user = current_user
      @event.release_issuing_certificates
      flash[:success] = "Emissão de certificado liberada com sucesso"
    else
      @event.errors.add(:base, "Preeencha a frequencia antes de liberar a emissão de certificados")
    end
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.current_user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, success: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    @event.current_user = current_user
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, success: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, success: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def verify_action
    redirect_to events_url, warning: 'A solicitação não pode ser alterada após o envio' if @event.draft?
  end

  private

  def set_filter_object
    @params = params[:filter] || {}
    @filter = Filter.new({
                             name: @params[:name],
                             event_category: @params[:event_category],
                             situation: @params[:situation],
                             start_date: @params[:start_date],
                             closing_date: @params[:closing_date],
                             show_filter: @params[:show_filter],
                         })
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_list_for_select
    @event_categories = EventCategory.select(:name, :id).map { |k, v| [k.name, k.id] }
    @courses = Course.select(:name, :id).map { |k, v| [k.name, k.id] }
    @key_situations = Situation.where(origin_type: Event.to_s).select('key_situation_id').distinct
                          .map { |k, v| [k.key_situation.description, k.key_situation.id] }
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :start_date, :closing_date, :event_category_id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    return unless params[:event].present?
    params.require(:event).permit(:name,
                                  :start_date,
                                  :closing_date,
                                  :event_category_id,
                                  :workload,
                                  image_attributes: [:id, :file],
                                  oriented_activities_attributes: [:id,
                                                                   :event_category_id,
                                                                   :title,
                                                                   :_destroy,
                                                                   person_ids: [],
                                                                   guideds_attributes: [:id,
                                                                                        :person_id,
                                                                                        :course_id,
                                                                                        :_destroy,
                                                                                        :semester],],
                                  child_events_attributes: [:id,
                                                            :_destroy,
                                                            :name,
                                                            :start_date,
                                                            :closing_date,
                                                            :event_category_id,
                                                            :workload],
                                  people_attributes: [:id, :_destroy])
  end
end

app/views/events/_fields.html.erb
<div class="col-md-6">
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: true %>
  </div>
</div>
<div class="col-md-3">
  <%= f.date_time_picker :start_date, placeholder: true %>
</div>
<div class="col-md-3">
  <%= f.date_time_picker :closing_date, placeholder: true %>
</div>
<div class="col-md-6">
  <div class="form-group">
    <%= f.label :event_category_id %>
    <%= f.select(:event_category_id, @event_categories,
                 { include_blank: true },
                 { size: 5,
                   class: 'form-control choices',
                   data: { trigger: '' }, }) %>
  </div>
</div>
<div class="col">
  <div class="form-group">
    <%= f.label :workload %>
    <%= f.number_field :workload, class: 'form-control', placeholder: true %>
  </div>
</div>
<%= f.fields_for :image, f.object.image ||= f.object.build_image do |ff| %>
  <div class="col-sm-auto">
    <% url = ff.object.url %>

    <%= ff.hidden_field :id %>
    <%= ff.image_field(:file, 'Procurar', 'Alterar', value: url) %>
  </div>
<% end %>

<div class="col-sm-12">
  <h5>Atividades Orientadas</h5>
</div>
<div class="col-sm-12 mt-3">
  <%= f.nested_fields_for :oriented_activities, f.object.oriented_activities do |ff| %>
    <%= ff.hidden_field :id %>
    <div class="col-sm-12 form-area bg-secondary mb-4">
      <div class="row">
        <div class="col-sm-6">
          <%= ff.label :title %>
          <%= ff.text_field :title, class: 'form-control', placeholder: true %>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <%= ff.label :event_category_id %>
            <%= ff.select(:event_category_id, @event_categories,
                          { include_blank: true },
                          { size: 5,
                            class: 'form-control choices' }) %>
          </div>
        </div>

        <div class="col">
          <div class="form-group">
            <%= ff.label :person_ids %>
            <%= ff.select(:person_ids, ff.object.people.map { |v| [v.full_name, v.id] },
                          { include_blank: true },
                          { size: 5,
                            multiple: true,
                            class: 'form-control choices-ajax',
                            data: { 'search-text': 'Digite o CPF do orientador que deseja selecionar',
                                    'search-mask': '000.000.000-00',
                                    'search-min': 14,
                                    'search-url': people_autocomplete_by_cpf_path }, }) %>
          </div>
        </div>

        <div class="col-auto">
          <%= ff.remove_nested_fields_link span_icon('', 'trash'), class: 'btn btn-danger no-label', role: 'button' %>
        </div>
        <div class="col-sm-12">
          <h6>Orientandos</h6>
        </div>
        <div class="col-sm-12 mt-3">
          <%= ff.nested_fields_for :guideds, ff.object.guideds do |fff| %>
            <%= fff.hidden_field :id %>
            <%= fff.hidden_field :person_id, class: 'person-hidden-field' %>
            <div class="col-sm-12 form-area bg-white mb-4">
              <div class="row">
                <div class="col-sm-3">
                  <div class="form-group">
                    <% cpf = fff.object.person.cpf if fff.object.person.present? %>
                    <%= label_tag :cpf, i18n_model(:person, :cpf) %>
                    <%= text_field_tag :cpf, cpf, class: 'form-control cpf-mask cpf-guided-field' %>
                  </div>
                </div>
                <div class="col-sm-9">
                  <div class="form-group">
                    <% full_name = fff.object.person.full_name if fff.object.person.present? %>
                    <%= label_tag :nome, i18n_model(:person, :name) %>
                    <%= text_field_tag :nome, full_name, class: 'form-control name-guided-field', disabled: true %>
                  </div>
                </div>
                <div class="col">
                  <div class="form-group">
                    <%= fff.label :course_id %>
                    <%= fff.select(:course_id, @courses,
                                   { include_blank: true },
                                   { size: 5,
                                     class: 'form-control choices',
                                     data: { trigger: '' }, }) %>
                  </div>
                </div>
                <div class="col-sm-auto">
                  <div class="form-group">
                    <%= fff.label :semester %>
                    <%= fff.number_field :semester, class: 'form-control choices' %>
                  </div>
                </div>
                <div class="col-auto">
                  <%= fff.remove_nested_fields_link span_icon('', 'trash'), class: 'btn btn-danger no-label', role: 'button' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-sm-12">
          <%= ff.add_nested_fields_link :guideds, span_icon('Adicionar Orientando', 'plus'), class: 'btn btn-sm
              btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="col-sm-12">
  <div class="form-group">
    <%= f.add_nested_fields_link :oriented_activities, span_icon('Adicionar Atividade Orientada', 'plus'), class: 'btn btn-sm btn-default' %>
  </div>
</div>
<div class="col-sm-12 mt-3">
  <h5>Subeventos</h5>

  <%= f.nested_fields_for :child_events, f.object.child_events do |ff| %>
    <%= validations_errors(ff.object) %>
    <%= ff.hidden_field :id %>
    <div class="col-sm-12 form-area bg-secondary mb-4">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= ff.label :name %>
            <%= ff.text_field :name, class: 'form-control', placeholder: true %>
          </div>
        </div>
        <div class="col-md-3">
          <%= ff.date_time_picker :start_date, placeholder: true %>
        </div>
        <div class="col-md-3">
          <%= ff.date_time_picker :closing_date, placeholder: true %>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= ff.label :event_category_id %>
            <%= ff.select(:event_category_id, @event_categories,
                          { include_blank: true },
                          { size: 5,
                            class: 'form-control choices',
                            data: { trigger: '' }, }) %>
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <%= ff.label :workload %>
            <%= ff.number_field :workload, class: 'form-control', placeholder: true %>
          </div>
        </div>
        <div class="col-sm-auto">
          <%= ff.remove_nested_fields_link span_icon('', 'trash'), class: 'btn btn-danger no-label', role: 'button' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="col-sm-12 mt-3">
  <div class="form-group">
    <%= f.add_nested_fields_link :child_events, span_icon('Adicionar Subevento', 'plus'), class: 'btn btn-sm btn-default' %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, html: { multipart: true }) do |f| %>
  <%= validations_errors(f.object) %>
  <div class="row">
    <%= render 'fields', f:f %>
  </div>

  <div class="clearfix">
    <div class="float-right">
      <%= link_to span_icon(i18n_word(:come_back), 'arrow-left'), :back,
                  class: 'btn btn-secondary btn-icon btn-1 btn-simple' %>
      <%= button_tag(:class => "btn btn-primary btn-icon btn-1 btn-simple") do %>
        <span><i class="fa fa-floppy-o mr-1"></i> Salvar</span>
      <% end %>
    </div>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(document).on('fieldsadded', (event) => {
        $(event.target).find('.cpf-guided-field').bind('keyup', searchPersonName);
    })
    function searchPersonName(event) {
        const people_name_path = '<%= people_name_path %>'
        const input = $(event.target)

        const setName = function (response) {
            if (response !== null) {
                input.closest("fieldset").find(".name-guided-field").val(`${response.name} ${response.surname}`)
                input.closest("fieldset").find(".person-hidden-field").val(response.id)
            } else {
                input.closest("fieldset").find(".name-guided-field").val('')
                input.closest("fieldset").find(".person-hidden-field").val('')
            }
        }

        if (input.val().length === 14) {
            ajaxGet(people_name_path, {cpf: input.val()}, setName, input);
        }
    }
</script>

app/views/events/_show.html.erb
<div class="col-md-6">
  <div class="form-group">
    <%= output_tag :name, event, event.name %>
  </div>
</div>
<div class="col-md-3">
  <div class="form-group">
    <%= output_tag :start_date, event, event.start_date.strftime('%d/%m/%Y %H:%M') %>
  </div>
</div>
<div class="col-md-3">
  <div class="form-group">
    <%= output_tag :closing_date, event, event.start_date.strftime('%d/%m/%Y %H:%M') %>
  </div>
</div>
<div class="col-md-5">
  <div class="form-group">
    <%= output_tag :event_category_id, event, event.event_category.name %>
  </div>
</div>
<div class="col">
  <div class="form-group">
    <%= output_tag :workload, event, "#{event.workload} Horas" %>
  </div>
</div>
<% if event.image.present? %>
  <div class="col-auto">
    <div class="form-group">
      <%= label_tag :image, i18n_model(:event, :image) %>
      <div>
        <%= view_image_button(event.image.url, i18n_model(:event, :image), button_text: 'Visualizar') %>
      </div>
    </div>
  </div>
<% end %>

<% if event.oriented_activities.any? %>
  <div class="col-sm-12">
    <h5>Atividades Orientadas</h5>
  </div>
  <div class="col-sm-12 mt-3">
    <% event.oriented_activities.each do |oriented_activity| %>
      <div class="col-sm-12 form-area bg-secondary mb-4">
        <div class="row">
          <div class="col-sm-8">
            <%= output_tag :title, oriented_activity, oriented_activity.title %>
          </div>
          <div class="col">
            <div class="form-group">
              <%= output_tag :event_category_id, event, oriented_activity.event_category.name %>
            </div>
          </div>
          <div class="col-sm-12">
            <h6>Orientandos</h6>
          </div>
          <div class="col-sm-12 mt-3">
            <% oriented_activity.guideds.each do |guided| %>
              <div class="col-sm-12 form-area bg-white mb-4">
                <div class="row">
                  <div class="col-sm-3">
                    <div class="form-group">
                      <%= output_tag :cpf, guided.person, guided.person.cpf %>
                    </div>
                  </div>
                  <div class="col-sm-9">
                    <div class="form-group">
                      <%= output_tag :name, guided.person, guided.person.full_name %>
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-group">
                      <%= output_tag :course_id, guided, guided.course.name %>
                    </div>
                  </div>
                  <div class="col-sm-auto">
                    <div class="form-group">
                      <%= output_tag :semester, guided, "#{guided.semester}º Semestre" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<% if event.child_events.any? %>
  <div class="col-sm-12 mt-3">
    <h5>Subeventos</h5>
    <% event.child_events.each do |child_event| %>
      <div class="col-sm-12 form-area bg-secondary mb-4">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= output_tag :name, child_event, child_event.name %>
            </div>
          </div>
          <div class="col-md-3">
            <%= output_tag :start_date, child_event, child_event.start_date.strftime('%d/%m/%Y %H:%M') %>
          </div>
          <div class="col-md-3">
            <%= output_tag :closing_date, child_event, child_event.closing_date.strftime('%d/%m/%Y %H:%M') %>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= output_tag :event_category_id, child_event, child_event.event_category.name %>
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <%= output_tag :workload, child_event, "#{child_event.workload} Hora (s)" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= page_title('Editar Evento') %>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="clearfix">
  <div class="float-left">
    <%= page_title('Eventos') %>
  </div>
  <div class="float-right pt-2 ">
    <%= icon_link 'Cadastrar', 'plus', new_event_path %>
  </div>
  <div class="float-right pt-2 mr-4">
    <%= icon_link i18n_word(:filter), 'filter', "#collapseFilter", class: 'text-dark', data: { toggle: 'collapse' },
                  aria: { expanded: "false", controls: "collapseFilter" } %>
  </div>
</div>

<%= card_filter(params[:show_filter]) do %>
  <%= form_for(@filter, url: events_path, local: true, method: :get, id: 'new_filter') do |f| %>
    <%= hidden_field_tag :show_filter, value: true %>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.text_field :name, class: 'form-control', placeholder: i18n_placeholder(:event, :name) %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.select(:event_category, @event_categories,
                       { include_blank: i18n_placeholder(:event, :event_category) },
                       { class: 'form-control choices',
                         data: { trigger: '' }, }) %>
        </div>
      </div>
      <div class="col-md-3">
        <% f.object.situation %>
        <%= f.select(:situation, @key_situations,
                     { include_blank: i18n_placeholder(:event_request, :situation) },
                     { class: 'choices' }) %>
      </div>
      <div class="col-md-2">
        <%= f.date_picker :start_date, placeholder: i18n_placeholder(:event, :start_date), hide_label: true %>
      </div>
      <div class="col-md-2 mr-auto">
        <%= f.date_picker :closing_date, placeholder: i18n_placeholder(:event, :closing_date), hide_label: true  %>
      </div>
      <div class="col-md-auto nowrap">
        <%= button_tag(:class => "btn btn-primary btn-icon btn-1 btn-simple pull") do %>
          <span><i class="fa fa-search"></i></span>
        <% end %>
        <%= clear_form_button %>
      </div>
    </div>
  <% end %>
<% end %>

<table class="table">
  <thead class="thead-light">
  <tr class="bg-primary">
    <th class="bold break-text">
      Nome
    </th>
    <th class="bold break-text">
      Categoria
    </th>
    <th class="bold">
      Situação
    </th>
    <th class="bold">
      Data de Inicio
    </th>
    <th class="bold">
      Data de Encerramento
    </th>
    <th style="width: 1%;" class="text-center bold">
      Ações
    </th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td class="break-text">
        <%= event.name %>
      </td>
      <td>
        <%= event.event_category.name%>
      </td>
      <td>
        <%= event.situation.situation_description %>
      </td>
      <td>
        <%= event.start_date.strftime('%d/%m/%Y') %>
      </td>
      <td>
        <%= event.closing_date.strftime('%d/%m/%Y') %>
      </td>
      <td class="text-center">
        <%= link_to span_icon('', 'search'), event,
                    class: 'btn btn-primary btn-icon btn-sm btn-simple', title: "Visualizar",
                    data: { toggle: 'tooltip', placement: 'bottom' } if event.can_action?(:show) %>
        <%= link_to span_icon('', 'list'), edit_frequences_path(event: event),
                    class: 'btn btn-icon btn-sm btn-default', title: "Visualizar ou preencher frequência",
                    data: { toggle: 'tooltip', placement: 'bottom' } if event.can_action?(:edit_frequences) %>
        <%= link_to span_icon('', 'certificate'), release_issuing_certificates_event_path(event),
                    class: 'btn btn-icon btn-sm btn-success', remote: true,
                    data: { toggle: 'tooltip', placement: 'bottom', confirm: 'Você tem certeza?' },
                    title: "Liberar emissão de certificados" if event.can_action?(:release_issuing_certificates) %>
        <%= link_to span_icon('', 'edit'), edit_event_path(event),
                    class: 'btn btn-icon btn-sm btn-primary',
                    data: { toggle: 'tooltip', placement: 'bottom' }, title: "Editar" if event.can_action?(:edit) %>
        <%= link_to span_icon('', 'trash'), event,
                    method: :delete, data: { confirm: 'Você tem certeza?', toggle: 'tooltip', placement: 'bottom' }, title: "Excluir",
                    class: 'btn btn-icon btn-sm btn-danger' if event.can_action?(:destroy) %>
      </td>
    </tr>

  <% end %>
  </tbody>
</table>

<div class="row justify-content-center">
  <%= paginate @events %>
</div>

app/views/events/new.html.erb
<%= page_title('Novo Evento') %>

<%= render 'form', event: @event %>

app/views/events/release_issuing_certificates.js.erb
<% if @event.errors.any? %>
  Swal.fire({
      icon: 'error',
      title: 'Impossível Liberar',
      html: '<%= j @event.errors.full_messages.join(', ').html_safe %>',
  })
<% else %>
  showSpinner();
  window.location.replace('<%= events_path %>');
<% end %>

app/views/events/show.html.erb
<%= page_title('Visualizar Evento') %>

<div class="row">
  <%= render 'show', event: @event %>
</div>

<div class="clearfix">
  <div class="float-right">
    <%= link_to span_icon(i18n_word(:come_back), 'arrow-left'), :back,
                class: 'btn btn-secondary btn-icon btn-1 btn-simple' %>
    <%= link_to span_icon(i18n_word(:edit), 'edit'), edit_event_path(@event),
                class: 'btn btn-primary btn-icon btn-1 btn-simple',
                data: { toggle: 'tooltip', placement: 'bottom' }, title: "Editar" %>
  </div>
</div>