config/routes.rb
Rails.application.routes.draw do
  resources :participants, path: 'paticipantes', except: [:index] do
    member do
      get :certificates_download, action: 'certificates_download'
    end
    collection do
      get :index
      post :import_from_csv
    end
  end
  resources :frequences, path: 'frequencia', except: [:edit, :destroy, :create] do
    collection do
      get :edit
    end
  end
  resources :type_participations, path: 'tipos-participacao'
  resources :certificate_templates, path: 'templates-de-certificados' do
    collection do
      get :load_selected_signatures
    end
    member do
      get 'arquive'
      get 'unarchive'
    end
  end
  resources :event_requests, path: 'solicitacoes-eventos' do
    member do
      get 'forward_the_request', action: 'forward_the_request'
      get 'generate_event', action: 'generate_event'
      post 'return_for_changes', action: 'return_for_changes'
    end
    collection do
      get 'my_requests'
    end
  end
  resources :courses, path: 'cursos'
  resources :events, path: 'eventos' do
    member do
      get 'release_issuing_certificates', action: 'release_issuing_certificates'
    end
  end
  resources :event_categories, path: 'categorias-de-eventos'
  resources :certificate_signatures, path: 'assinaturas-de-certificado' do
    collection do
      get 'autocomplete_by_name_or_role'
    end
    member do
      get 'arquive'
      get 'unarchive'
    end
  end
  resources :permissions, path: 'permissoes', except: [:new, :destroy] do
    collection do
      get 'recreate_and_update_all'
    end
  end
  resources :profiles, path: 'perfis'
  devise_for :users,
             controllers: { omniauth_callbacks: "omniauth_callbacks" },
             :skip => [:registrations]

  resources :users, path: 'usuarios' do
    collection do
      get 'new_registration'
      get 'success_registration'
      post 'registration_save'
    end
  end

# get 'users/:id/complete_registration', to: 'users#complete_registration'

  get 'people/name', to: 'people#name'
  get 'validar/:certificate_hash', to: 'participants#validate_certificate'
  get 'validar/', to: 'participants#validate_certificate'
  get 'people/autocomplete_by_cpf', to: 'people#autocomplete_by_cpf'

  root to: "home#index"

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/certificate_template.rb
class CertificateTemplate < ApplicationRecord
  include CSituation

  belongs_to :image, required: false
  belongs_to :person, required: false
  belongs_to :event_category, required: false
  has_and_belongs_to_many :certificate_signatures

  before_validation :set_file_extensions
  after_update :set_default_template

  accepts_nested_attributes_for :image, allow_destroy: true, reject_if: -> (x) { x[:file].nil? }

  TAGS_TEMPLATES = {
      nome_aluno: 'Nome do Participante',
      carga_horaria: 'Carga Horária',
      nome_completo_evento: 'Nome Completo do Evento/Atividade',
      nome_evento: 'Nome do Evento/Atividade',
      tipo_participacao: 'Tipo de Participação',
      data_inicio: 'Data de Inicío',
      data_encerramento: 'Data de Encerramento',
  }.freeze

  def self.default_certificate(event_category_id)
    CertificateTemplate.where(default: true, event_category_id: event_category_id).order(updated_at: :desc).limit(1).first
  end


  def archive
    return if archived?

    self.situations.create(person: current_user.person,
                           observation: '',
                           key_situation: KeySituation.find_by(key: :archived)).save

    set_current_situation
  end

  def unarchive
    return unless archived?

    self.situations.create(person: current_user.person,
                           observation: '',
                           key_situation: KeySituation.find_by(key: :unarchived)).save

    set_current_situation
  end

  private

  # Defines the allowed image formats
  def set_default_template
    return unless default
    CertificateTemplate.where.not(id: self.id).where(default: true, event_category_id: event_category_id).each do |template|
      template.update_attribute(:default, false)
    end
  end

  # Defines the allowed image formats
  def set_file_extensions
    self.image.allowed_extensions = [:png, :jpg, :jpeg] if self.image.present?
  end
end

app/controllers/certificate_templates_controller.rb
class CertificateTemplatesController < ApplicationController

  load_and_authorize_resource
  before_action :set_list_for_select, only: [:index, :new, :edit, :update, :create]
  before_action :set_certificate_template, only: [:show, :edit, :update, :destroy]
  before_action :set_filter_object, only: [:index]

  # GET /certificate_templates
  def index
    @certificate_templates = FindCertificateTemplate.find(@filter, page_params)
  end

  # GET /certificate_templates/1
  def show
  end

  # GET /certificate_templates/new
  def new
    @certificate_template = CertificateTemplate.new
  end

  # GET /certificate_templates/1/edit
  def edit
  end

  # POST /certificate_templates
  def create
    @certificate_template = CertificateTemplate.new(certificate_template_params)
    @certificate_template.person = current_user.person

    if @certificate_template.save
      redirect_to @certificate_template, success: 'Certificate template was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /certificate_templates/1
  def update
    if @certificate_template.update(certificate_template_params)
      redirect_to @certificate_template, success: 'Certificate template was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /certificate_templates/1
  def destroy
    @certificate_template.destroy
    redirect_to certificate_templates_url, success: 'Certificate template was successfully destroyed.'
  end

  def load_selected_signatures
    @certificate_signatures = CertificateSignature.where(id: params[:selecteds])
  end

  def arquive
    @certificate_template.current_user = current_user
    @certificate_template.archive
    respond_to do |format|
      format.html { redirect_to certificate_templates_url, success: 'Template arquivado com sucesso.' }
    end
  end

  def unarchive
    @certificate_template.current_user = current_user
    @certificate_template.unarchive
    respond_to do |format|
      format.html { redirect_to certificate_templates_url, success: 'Template desarquivado com sucesso.' }
    end
  end

  private

  def set_filter_object
    @params = params[:filter] || {}
    if @params[:certificate_signatures].present?
      @certificate_signatures = CertificateSignature.where(id: @params[:certificate_signatures]).map { |v| ["#{v.name} - #{v.role}", v.id] }
    end
    @filter = Filter.new({
                             name: @params[:name],
                             event_category: @params[:event_category],
                             archived: Util.to_boolean(@params[:archived]),
                             certificate_signatures: @params[:certificate_signatures],
                         })
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_certificate_template
    @certificate_template = CertificateTemplate.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_list_for_select
    @event_categories = EventCategory.select(:name, :id).map { |k, v| [k.name, k.id] }
  end

  # Only allow a trusted parameter "white list" through.
  def certificate_template_params
    return nil unless params[:certificate_template].present?
    params.require(:certificate_template).permit(:body, :event_category_id, :default,
                                                 image_attributes: [:file],
                                                 certificate_signature_ids: [])
  end

  def send_invoice_pdf
    send_file invoice_pdf.to_pdf,
              filename: invoice_pdf.filename,
              type: "application/pdf",
              disposition: "inline"
  end
end

app/views/certificate_templates/_form.html.erb
<div class="nav-wrapper">
  <ul class="nav nav-pills nav-fill flex-column flex-md-row" id="tabs-icons-text" role="tablist">
    <li class="nav-item">
      <a class="nav-link mb-sm-3 mb-md-0 active" id="form-tab" data-toggle="tab" href="#form" role="tab"
         aria-controls="form" aria-selected="true">
        <i class="ni ni-ruler-pencil mr-2"></i>
        Criar
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link mb-sm-3 mb-md-0" id="preview-tab" data-toggle="tab" href="#preview" role="tab"
         aria-controls="preview" aria-selected="false">
        <i class="ni ni-image mr-2"></i>
        Pré Visualizar
      </a>
    </li>
  </ul>
</div>
<div class="card shadow">
  <div class="card-body">
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="form" role="tabpanel" aria-labelledby="form-tab">
        <%= form_with(model: certificate_template, local: true, html: { multipart: true }) do |f| %>
          <%= validations_errors(f.object) %>
          <div class="row">
            <%= f.fields_for :image, f.object.image ||= f.object.build_image do |ff| %>
              <div class="col-sm-auto">
                <% url = ff.object.url %>

                <%= ff.hidden_field :id %>
                <%= ff.image_field(:file, 'Procurar', 'Alterar', id: 'fileinput', value: url) %>
              </div>
            <% end %>
            <div class="col-md">
              <div class="form-group">
                <%= f.label :event_category %>
                <%= f.select(:event_category_id, @event_categories,
                             { include_blank: true },
                             { size: 5, 'max-items': 4,
                               class: 'form-control choices',
                               data: { trigger: '' }, }) %>
              </div>
            </div>
            <div class="col-sm-auto">
              <div class="form-group">
                <div class="custom-control custom-checkbox">
                  <%= f.check_box :default, class: 'custom-control-input' %>
                  <%= f.label :default, class: 'custom-control-label' %>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <%= f.label :body %>
                <%= f.summernote_area :body, class: 'form-control', placeholder: true, onchange: 'changeText(this)' %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <div class="form-group">
                  <%= f.label :certificate_signatures %>
                  <%= f.select(:certificate_signature_ids, f.object.certificate_signatures.map { |v| ["#{v.name} - #{v.role}", v.id] },
                               { include_blank: true },
                               { size: 5,
                                 multiple: true,
                                 class: 'form-control choices-ajax',
                                 data: { 'search-text': 'Digite o nome da assinatura',
                                         'search-min': 3,
                                         'search-url': autocomplete_by_name_or_role_certificate_signatures_path }, }) %>
                </div>
              </div>
            </div>
          </div>

          <div class="clearfix">
            <div class="float-right">
              <%= link_to span_icon(i18n_word(:come_back), 'arrow-left'), :back,
                          class: 'btn btn-secondary btn-icon btn-1 btn-simple' %>
              <%= button_tag(:class => "btn btn-primary btn-icon btn-1 btn-simple") do %>
                <span><i class="fa fa-floppy-o mr-1"></i> <%= i18n_word(:save) %></span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="preview" role="tabpanel" aria-labelledby="preview-tab">
        <%= render 'show', certificate_template: certificate_template %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(() => {
        const choices_signatures = document.getElementById('certificate_template_certificate_signature_ids')

        choices_signatures.addEventListener('removeItem', onChangeSignatures, true,);
        choices_signatures.addEventListener('addItem', onChangeSignatures, true,);

        $("#preview-tab").on("click", function () {
            changeText();
            changeImage();
        });

        createSummernoteWithCustomMenu();
    })

    // Creates a customized summernote for editing templates
    function createSummernoteWithCustomMenu() {
        const contents = '<%= j CertificateTemplate::TAGS_TEMPLATES.to_a.map{ |tag, descricao|
                              content_tag(:li, descricao, class: 'pl-3 pr-3 cursor-pointer nowrap',  data: {tag: "#{tag}"},  style: '')
                          }.join('').html_safe %>'

        const hightlightButton = function (context) {
            const ui = $.summernote.ui;

            const pdfButton = ui.buttonGroup([
                ui.button({
                    className: "dropdown-toggle",
                    contents: '<span class="fa fa-tag mr-1"></span> <span class="caret">Tags</span>',
                    tooltip: "Escolha tags para serem substituídas por dados reais",
                    callback: (button) => {
                        button.click(function () {
                            context.invoke('editor.saveRange');
                        });
                    },
                    data: {
                        toggle: "dropdown",
                    },
                }),
                ui.dropdown({
                    className: "drop-default summernote-list",
                    style: 'width: 100px',
                    contents: contents,
                    callback: function ($dropdown) {
                        $dropdown.find("li").click(function (target) {
                            insertAtTemplate(`{{${$(target.currentTarget).data('tag')}}} `)
                        });
                    },
                }),
            ]);


            return pdfButton.render();
        }

        $('#certificate_template_body').summernote({
            height: 200,
            fontSizes: ['8', '9', '10', '11', '12', '14', '18', '20', '22', '24', '26', '28', '30'],
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', ['fontname', 'strikethrough', 'superscript', 'subscript']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['tags', ['tags']]
            ],
            buttons: {
                tags: hightlightButton
            },
        })
    }

    // Insert text in summernote without losing formatting
    function insertAtTemplate(text) {
        const templateInput = $('#certificate_template_body')
        let newRange = templateInput.summernote("getLastRange").deleteContents();

        newRange.sc.textContent = newRange.sc.textContent.substring(0, newRange.so) + text + newRange.sc.textContent.substring(newRange.so, newRange.sc.textContent.length);
        templateInput.summernote('setLastRange', $.summernote.range.create(newRange.sc, newRange.so + text.length).select());

        $(".summernote").triggerHandler("summernote.change");
    }

    function changeImage() {
        const url = $('#fileinput-image').attr('src')
        $('#certificate-frame').css('background-image', `url(${url})`);
    }

    // Event that updates the text in the template preview
    function changeText() {
        const certificate_text_frame = $('#certificate-text-content');
        certificate_text_frame.html($('#certificate_template_body').val());
    }

    // Event that updates the signatures of the template preview
    function onChangeSignatures(event) {
        $.ajax({
            data: {
                selecteds: $(event.target).val()
            },
            type: "GET",
            url: "<%= load_selected_signatures_certificate_templates_path %>",
            dataType: "script"
        });
    }
</script>

app/views/certificate_templates/_show.html.erb
<div id="certificate-frame">
  <div id="certificate-text-frame">
    <div id="certificate-text-content">
    </div>
  </div>
  <div id="certificate-signatures-frame">
    <%= render 'view_certificate_signatures', certificate_signatures: certificate_template.certificate_signatures %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(() => {
        loadPreview();
        loadData();
    })

    function loadData() {
        <% unless certificate_template.new_record? %>
          $('#certificate-frame').css('background-image', `url(<%= certificate_template.image.url %>)`)
          $('#certificate-text-content').html('<%= j certificate_template.body.html_safe %>')
        <% end %>
    }

    // Generates template preview layout
    function loadPreview() {
        const heigth_a4_ref = 807.467
        const width_a4_ref = 1142

        const certificate_frame = $('#certificate-frame');
        const certificate_text_frame = $('#certificate-text-frame');
        const certificate_signatures_frame = $('#certificate-signatures-frame');

        const width = $('#form').width() || certificate_frame.parent().width();
        const height = parseInt(width) * heigth_a4_ref / width_a4_ref;

        certificate_frame.css('height', height);

        const top_text = parseInt(height) * 310 / heigth_a4_ref;
        const height_text = parseInt(height) * 220 / heigth_a4_ref;

        certificate_text_frame.css({
            'top': `${top_text}px`,
            'height': `${height_text}px`,
            'padding-left': '100px',
            'line-height': `${height_text}px`,
            'padding-right': '100px',
        });

        const top_signatures = (parseInt(height) * 570 / heigth_a4_ref) - height_text;

        certificate_signatures_frame.css({
            'top': `${top_signatures}px`,
            'padding-left': '100px',
            'padding-right': '100px',
        });

    }
</script>

app/views/certificate_templates/_view_certificate_signatures.html.erb
<div id="" class="col-md-12">
  <div class="row">
    <% certificate_signatures.each do |certificate_signature| %>
      <div class="col text-center">
        <img id="scanned-signature" class="scanned-signature"
             src="<%= certificate_signature.image.url %>"
             alt="<%= certificate_signature.name %>"/>
        <span id="name" class="d-block text-black font-weight-bold font-italic"><%= certificate_signature.name %></span>
        <span id="role" class="d-block"><%= certificate_signature.role %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/certificate_templates/edit.html.erb
<%= page_title("#{i18n_word(:edit)} #{i18n_model(:certificate_template)}") %>

<%= render 'form', certificate_template: @certificate_template %>

app/views/certificate_templates/index.html.erb
<div class="clearfix">
  <div class="float-left">
    <%= page_title(i18n_model(:certificate_template, plural: true)) %>
  </div>
  <div class="float-right pt-2">
    <%= icon_link i18n_word(:register), 'plus', new_certificate_template_path %>
  </div>
  <div class="float-right pt-2 mr-4">
    <%= icon_link i18n_word(:filter), 'filter', "#collapseFilter", class: 'text-dark', data: { toggle: 'collapse' },
                  aria: { expanded: "false", controls: "collapseFilter" } %>
  </div>
</div>

<%= card_filter(params[:show_filter]) do %>
  <%= form_for( @filter, url: certificate_templates_path, method: :get, id: 'new_filter') do |f| %>
    <%= hidden_field_tag :show_filter, value: true %>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= f.select(:event_category, @event_categories,
                       { include_blank: i18n_placeholder(:certificate_template, :event_category) },
                       { class: 'form-control choices',
                         data: { trigger: '' }, }) %>
        </div>
      </div>
      <div class="col-md-5 mr-auto">
        <div class="form-group">
          <div class="form-group">
            <%= f.select(:certificate_signatures, @certificate_signatures || [],
                         { include_blank: true },
                         { multiple: true,
                           placeholder: 'Assinaturas',
                           class: 'form-control choices-ajax',
                           data: { 'search-text': 'Digite o nome da assinatura', 'search-min': 3,
                                   'search-url': autocomplete_by_name_or_role_certificate_signatures_path }, }) %>
          </div>
        </div>
      </div>
      <div class="mr-auto">
        <div class="form-group">
          <div class="custom-control mt-2">
            <%= f.check_box :archived, { class: 'custom-control-input' }, true, false %>
            <%= f.label :archived, 'Arquivado?', class: 'custom-control-label' %>
          </div>
        </div>
      </div>
      <div class="col-md-auto nowrap">
        <%= button_tag(:class => "btn btn-primary btn-icon btn-1 btn-simple pull") do %>
          <span><i class="fa fa-search"></i></span>
        <% end %>
        <%= clear_form_button %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row">
  <DIV class="col-sm-12">
    <table class="table">
      <thead class="thead-light">
      <tr class="bg-primary">
        <th class="bold"><%= i18n_model(:certificate_template, :event_category) %></th>
        <th class="bold break-text"><%= i18n_model(:certificate_template, :body) %></th>
        <th class="bold"><%= i18n_model(:certificate_template, :certificate_signatures) %></th>
        <th class="text-center">Arquivado?</th>
        <th class="text-center bold" colspan="3"><%= i18n_word(:actions) %></th>
      </tr>
      </thead>

      <tbody>
      <% @certificate_templates.each do |certificate_template| %>
        <tr>
          <td>
            <%= certificate_template.event_category.name %>
          </td>
          <td class="break-text">
            <%= truncate(strip_tags(certificate_template.body), length: 170) %>
          </td>
          <td>
            <% certificate_template.certificate_signatures.each do |certificate_signature| %>
              <span class="badge badge-default"><%= certificate_signature.name %></span>
            <% end %>
          </td>
          <td class="text-center">
            <%= certificate_template.archived? ? 'SIM' : 'NÃO' %>
          </td>
          <td class="text-center">
            <%= link_to span_icon('', 'search'), certificate_template,
                        class: 'btn btn-primary btn-icon btn-sm btn-simple',
                        data: { toggle: 'tooltip', placement: 'bottom' }, title: "Visualizar" %>
            <%= link_to span_icon('', 'edit'), edit_certificate_template_path(certificate_template),
                        class: 'btn btn-icon btn-sm btn-warning',
                        data: { toggle: 'tooltip', placement: 'bottom' }, title: "Editar" %>
            <%= link_to span_icon('', 'trash'), certificate_template,
                        method: :delete, data: { confirm: 'Você tem certeza?', toggle: 'tooltip', placement: 'bottom' }, title: "Excluir",
                        class: 'btn btn-icon btn-sm btn-danger' %>
            <%= link_to span_icon('', 'archive'), arquive_certificate_template_path(certificate_template),
                        method: :get, data: { confirm: 'Você tem certeza?', toggle: 'tooltip', placement: 'bottom' }, title: "Arquivar",
                        class: 'btn btn-icon btn-sm btn-default' unless certificate_template.archived? %>
            <%= link_to span_icon('', 'undo'), unarchive_certificate_template_path(certificate_template),
                        method: :get, data: { confirm: 'Você tem certeza?', toggle: 'tooltip', placement: 'bottom' }, title: "Desarquivar",
                        class: 'btn btn-icon btn-sm btn-default' if certificate_template.archived? %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </DIV>
</div>

<div class="row justify-content-center">
  <%= paginate @certificate_templates %>
</div>

app/views/certificate_templates/load_selected_signatures.js.erb
$('#certificate-signatures-frame').html('<%= j render 'view_certificate_signatures', certificate_signatures: @certificate_signatures %>')

app/views/certificate_templates/new.html.erb
<%= page_title("#{i18n_word(:new)} #{i18n_model(:certificate_template)}") %>

<%= render 'form', certificate_template: @certificate_template %>

app/views/certificate_templates/show.html.erb
<%= page_title("#{i18n_word(:view)} #{i18n_model(:certificate_template)}") %>

<div class="row">
  <div class="col-sm-12">
    <%= render 'show', certificate_template: @certificate_template %>
  </div>
</div>

<div class="clearfix mt-4">
  <div class="float-right">
    <%= link_to span_icon(i18n_word(:come_back), 'arrow-left'), :back,
                class: 'btn btn-secondary btn-icon btn-1 btn-simple' %>
    <%= link_to span_icon(i18n_word(:edit), 'search'), edit_certificate_template_path(@certificate_template),
                class: 'btn btn-primary btn-icon btn-1 btn-simple',
                data: { toggle: 'tooltip', placement: 'bottom' }, title: "Editar" %>
  </div>
</div>